# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwcao4mEbvpu2E2bIMwpJdeYiucR6rBT
"""

!pip install streamlit

from tensorflow.keras.models import load_model

# Load your saved model
model = load_model('/content/best_model.keras')

import numpy as np
from PIL import Image

def predict(image_path):
    image = Image.open(image_path)
    image = image.resize((224, 224))  # Sesuaikan ukuran sesuai kebutuhan
    img_array = np.array(image) / 255.0  # Normalisasi jika perlu
    img_array = np.expand_dims(img_array, axis=0)  # Tambahkan batch dimensi
    prediction = model.predict(img_array)
    return prediction

import streamlit as st
from PIL import Image

st.title("Image Classification with Keras Model")

uploaded_file = st.file_uploader("Choose an image...", type="jpg")

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    st.write("Classifying...")
    prediction = predict(uploaded_file)
    st.write(f"Prediction: {prediction}")

#streamlit run nama_file.py